# Generated by Django 5.1.6 on 2025-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigyanraksha', '0002_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='details_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=50),
        ),
    ]
